@extends('layouts.app')
@section('stylesheet')
    <link rel="stylesheet" href="{{ asset('css/auth.css') }}">
@endsection
@section('content')
    <!--
   blade for login page, allows registered users to login
  mostly generated by laravel auth but has custom functionality
-->
    <div class="container d-flex justify-content-center flex-column align-items-center">
        <div class="card d-flex justify-content-center">
            <form method="POST" action="{{ route('login') }}">
                @csrf
                <div class="mb-4 text-center card-header">
                    <img src="{{ asset('/images/retracelogo.png') }}" alt="" height="40">
                    <h3><strong>re-trace.io</strong></h3>
                </div>
                <div class="card-body text-center">
                    <div class="form-group">
                        <label for="email" class="sr-only">Email address</label>
                        <input id="email" type="email" class="form-control text-center @error('email') is-invalid @enderror"
                               name="email" placeholder="{{ __('E-Mail Address') }}" value="{{ old('email') }}"
                               required
                               autocomplete="email" autofocus>

                        @error('email')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <label for="password" class="sr-only">Password</label>
                        <input id="password" type="password"
                               class="form-control text-center @error('password') is-invalid @enderror"
                               name="password" required autocomplete="current-password" placeholder="Password">

                        @error('password')
                        <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                        @enderror
                    </div>
                    <div class="form-group">
                        <div class="text-right">
                            @if (Route::has('password.request'))
                                <a class="btn btn-link" id="forgot-password" href="{{ route('password.request') }}">
                                    {{ __('Forgot Password?') }}
                                </a>
                            @endif
                        </div>
                    </div>
                    <div class="form-group row d-flex justify-content-center align-items-center">
                        <div class="form-check">
                            <input class="form-check-input" type="checkbox" name="remember"
                                   id="remember" {{ old('remember') ? 'checked' : '' }}>

                            <label class="form-check-label" for="remember">
                                Keep me logged in
                            </label>
                        </div>
                    </div>
                    <div class="form-group">
                        <div>
                            <button type="submit" class="btn btn-primary" id="main-button-wide">
                                {{ __('Log in') }}
                            </button>
                        </div>
                    </div>
                </div>
            </form>
            <div class="card-footer text-center" id="login-footer">
                <div>
                    <p>Don't have an account?  <strong><a href="{{ route('register') }}">{{ __('Sign up') }}</a></strong></p>

                </div>
            </div>
        </div>

    </div>
    <script type="text/javascript" language="JavaScript">
        document.forms['myform'].elements['mytextfield'].focus();
    </script>
@endsection
